### ISSUE TITLE
Fresh install and InvalidArgumentException: [WARNING 1549] ...

### ISSUE THREAD

**Issue by fabricek** [leaphly/leaphly-sandbox#12]
When i do a fresh install and run (wamp server)  i have this error. Please help.

InvalidArgumentException: [WARNING 1549] failed to load external entity "in_memory_buffer" (in n/a - line 0, column 0) [WARNING 3084] Element '{http://www.w3.org/2001/XMLSchema}import': Failed to locate a schema at location 'in_memory_buffer'. Skipping the import. (in in_memory_buffer - line 9, column 0) [ERROR 1845] Element '{http://friendsofsymfony.github.com/schema/rest}routes': No matching global declaration available for the validation root. (in file:///C:/wamp/www/leaphly/web/ - line 5, column 0) in C:\wamp\www\leaphly\vendor\friendsofsymfony\rest-bundle\FOS\RestBundle\Routing\Loader\RestXmlCollectionLoader.php on line 199

**Comment by fabricek** [comment]
The sandbox does not work out of the box (fatal error as described). This have to do with FOS rest bundle.
I remove the bundle Fos rest in the vendor folder and replace in composer.json "friendsofsymfony / rest-bundle": "1.1.*" instead of "~ 1.1". Make an composer update and the error gone. The site is now reachable with a new fatal error: Call to a member function getSingleResult() on a non-object in ...\leaphly\src\Acme\SimplePurchaseProcessBundle\Controller\CartController.php on line 19 that i'll try to solve if Giulio didn't care... ;)

**Comment by liuggio** [comment]
Hi, sorry for the troubles,
I just made a fresh install and it was ok, with no problem on fos rest.
