### ISSUE TITLE
Call to a member function getSingleResult() on a non-object

### ISSUE THREAD

**Issue by fabricek** [leaphly/leaphly-sandbox#13]
The Sandbox is really incomplete ! No possibity to add product and process payments out of the box and fatal errors.  It's a pity beceause we have a great documentation to learn and the sandbox doesn't work. However this is the trick to solve this error : 
In leaphly\src\Acme\SimplePurchaseProcessBundle\Controller\CartController.php comment like this :                                      ->findBy(array(), null, $limit = 1);
for conference and $ticketForm                  //->getSingleResult();
And modify
               array(
                'tshirt_form' => $shirtForm->createView(),
                'tshirt_product' => $productShirt[0],
                'ticket_form' => $ticketForm->createView(),
                'ticket_product' => $conference[0])
Now you can use the site without availabilty to put product in the cart and process payment.

**Comment by liuggio** [comment]
Fabrice is not complete, because is not stable,
but you could contribute, please make a PR with this changes.
